name: zecon
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - matplotlib=3.3.4
  - numpy=1.19.5
  - tqdm=4.62.3
  - pip:
    - opencv-python==4.7.0.72
    - tqdm==4.64.1
    - ftfy==6.0.3
    - kornia==0.6.4
    - mpi4py==3.1.3
    - regex
